<template>
  <div class="batch-task-page">
    <header class="page-header"><div><h2>批量创建任务（支持父子任务）</h2><span>可通过表格一次创建多个任务及其子任务</span></div><a-space><a-button @click="handleCancel">取消</a-button><a-button type="primary" :loading="submitting" @click="handleSubmit">确认创建</a-button></a-space></header>
    <a-card :bordered="false" class="batch-card defaults-card">
      <a-form layout="inline">
        <a-form-item label="所属项目" required><a-select v-model:value="defaults.projectId" :options="projectOptions" placeholder="请选择项目" show-search option-filter-prop="label" /></a-form-item>
        <a-form-item label="默认负责人"><a-select v-model:value="defaults.assigneeId" :options="userOptions" placeholder="请选择负责人" allow-clear show-search option-filter-prop="label" /></a-form-item>
        <a-form-item label="默认角色"><a-select v-model:value="defaults.roleName" :options="roleOptions" placeholder="请选择角色" allow-clear /></a-form-item>
        <a-form-item label="默认优先级"><a-select v-model:value="defaults.priority" :options="priorityOptions" /></a-form-item>
        <a-form-item label="默认计划时间"><a-range-picker v-model:value="defaults.planDates" value-format="YYYY-MM-DD" /></a-form-item>
        <a-button type="primary" @click="applyDefaults">应用到全部任务</a-button>
      </a-form>
    </a-card>
    <a-card :bordered="false" class="batch-card">
      <div class="toolbar"><a-space wrap><a-button type="primary" @click="addParent"><PlusOutlined />添加父任务</a-button><a-button :disabled="selectedKeys.length !== 1" @click="addChild(selectedKeys[0])"><PlusOutlined />添加子任务</a-button><a-button :disabled="selectedKeys.length !== 1" @click="duplicateRow(selectedKeys[0])">复制</a-button><a-button danger :disabled="!selectedKeys.length" @click="removeRows(selectedKeys)">删除</a-button></a-space><span>共 {{ rows.length }} 条任务（父任务 {{ parentRows.length }} 条，子任务 {{ rows.length - parentRows.length }} 条）</span></div>
      <div class="table-wrap"><table class="task-table"><thead><tr><th><a-checkbox :checked="allSelected" :indeterminate="partSelected" @change="toggleAll" /></th><th>序号</th><th>任务名称</th><th>角色</th><th>优先级</th><th>计划开始时间</th><th>计划结束时间</th><th>执行人</th><th>项目描述</th><th>标签</th><th>操作</th></tr></thead><tbody><tr v-for="row in displayRows" :key="row.key"><td><a-checkbox :checked="selectedKeys.includes(row.key)" @change="toggleRow(row.key)" /></td><td>{{ row.sequence }}</td><td><div class="name-cell" :style="{ paddingLeft: `${row.level * 20}px` }"><span v-if="row.level">└</span><a-input v-model:value="row.name" :placeholder="row.level ? '请输入子任务名称' : '请输入任务名称'" /></div></td><td><a-select v-model:value="row.roleName" :options="roleOptions" placeholder="请选择角色" allow-clear /></td><td><a-select v-model:value="row.priority" :options="priorityOptions" placeholder="请选择优先级" /></td><td><a-date-picker v-model:value="row.plannedStartDate" value-format="YYYY-MM-DD" placeholder="选择日期" /></td><td><a-date-picker v-model:value="row.plannedEndDate" value-format="YYYY-MM-DD" placeholder="选择日期" /></td><td><a-select v-model:value="row.assigneeId" :options="userOptions" placeholder="请选择执行人" allow-clear show-search option-filter-prop="label" /></td><td><a-textarea v-model:value="row.description" :auto-size="{ minRows: 1, maxRows: 3 }" placeholder="请输入项目描述" /></td><td><a-input v-model:value="row.tags" placeholder="请输入标签" /></td><td><a-space :size="4"><a-button type="link" size="small" @click="duplicateRow(row.key)">复制</a-button><a-button v-if="!row.parentKey" type="link" size="small" @click="addChild(row.key)">添加子任务</a-button><a-button type="link" danger size="small" @click="removeRows([row.key])">删除</a-button></a-space></td></tr></tbody></table></div>
    </a-card>
  </div>
</template>

<script setup>
import { PlusOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { createTask, getDicts, getProjectList, getSystemUsers } from '@/api/managementProject'

const router = useRouter()
const users = ref([]); const projects = ref([]); const priorityOptions = ref([]); const selectedKeys = ref([]); const submitting = ref(false)
const defaults = reactive({ projectId: undefined, assigneeId: undefined, roleName: '', priority: 'MEDIUM', planDates: [] })
const roleOptions = [{ label: '开发', value: '开发' }, { label: '测试', value: '测试' }]
let seed = 1
const newRow = parentKey => ({ key: `row-${seed++}`, parentKey: parentKey || null, name: '', roleName: defaults.roleName || '', priority: defaults.priority, assigneeId: defaults.assigneeId, plannedStartDate: defaults.planDates?.[0], plannedEndDate: defaults.planDates?.[1], description: '', tags: '' })
const rows = ref([newRow()])
const userOptions = computed(() => users.value.map(item => ({ label: item.realName, value: item.id })))
const projectOptions = computed(() => projects.value.map(item => ({ label: item.name, value: item.id })))
const parentRows = computed(() => rows.value.filter(row => !row.parentKey))
const displayRows = computed(() => { const result = []; parentRows.value.forEach((parent, index) => { parent.level = 0; parent.sequence = String(index + 1); result.push(parent); rows.value.filter(row => row.parentKey === parent.key).forEach((child, childIndex) => { child.level = 1; child.sequence = `${index + 1}.${childIndex + 1}`; result.push(child) }) }); return result })
const allSelected = computed(() => rows.value.length > 0 && selectedKeys.value.length === rows.value.length)
const partSelected = computed(() => selectedKeys.value.length > 0 && !allSelected.value)
const addParent = () => rows.value.push(newRow())
const addChild = key => { const parent = rows.value.find(row => row.key === key); if (!parent) return; const parentKey = parent.parentKey || parent.key; const child = newRow(parentKey); const lastIndex = Math.max(...rows.value.map((row, index) => row.key === parentKey || row.parentKey === parentKey ? index : -1)); rows.value.splice(lastIndex + 1, 0, child) }
const duplicateRow = key => { const source = rows.value.find(row => row.key === key); if (!source) return; rows.value.splice(rows.value.findIndex(row => row.key === key) + 1, 0, { ...source, key: `row-${seed++}`, name: source.name ? `${source.name}（副本）` : '' }) }
const removeRows = keys => { const remove = new Set(keys); keys.forEach(key => rows.value.filter(row => row.parentKey === key).forEach(row => remove.add(row.key))); rows.value = rows.value.filter(row => !remove.has(row.key)); selectedKeys.value = selectedKeys.value.filter(key => !remove.has(key)); if (!rows.value.length) addParent() }
const toggleRow = key => { selectedKeys.value = selectedKeys.value.includes(key) ? selectedKeys.value.filter(item => item !== key) : [...selectedKeys.value, key] }
const toggleAll = () => { selectedKeys.value = allSelected.value ? [] : rows.value.map(row => row.key) }
const applyDefaults = () => rows.value.forEach(row => Object.assign(row, { roleName: defaults.roleName || row.roleName, priority: defaults.priority || row.priority, assigneeId: defaults.assigneeId || row.assigneeId, plannedStartDate: defaults.planDates?.[0] || row.plannedStartDate, plannedEndDate: defaults.planDates?.[1] || row.plannedEndDate }))
const handleSubmit = async () => { if (!defaults.projectId) return message.warning('请选择所属项目'); if (rows.value.some(row => !row.name.trim() || !row.priority || !row.assigneeId)) return message.warning('请完善任务名称、优先级和执行人'); submitting.value = true; try { const ids = new Map(); for (const row of displayRows.value) { const result = await createTask({ projectId: defaults.projectId, parentId: row.parentKey ? ids.get(row.parentKey) : undefined, name: row.name.trim(), roleName: row.roleName || undefined, priority: row.priority, assigneeId: row.assigneeId, plannedStartDate: row.plannedStartDate || undefined, plannedEndDate: row.plannedEndDate || undefined, description: row.description || undefined, tags: row.tags || undefined }); ids.set(row.key, result.id) } message.success('任务批量创建成功'); router.push({ name: 'AllTasks' }) } catch (error) { message.error(error.message || '任务批量创建失败') } finally { submitting.value = false } }
const handleCancel = () => router.push({ name: 'AllTasks' })
onMounted(async () => { try { const [dicts, userResult, projectResult] = await Promise.all([getDicts(), getSystemUsers({ pageNo: 1, pageSize: 200, enabled: true }), getProjectList({ pageNo: 1, pageSize: 200, projectType: 'MANAGEMENT' })]); users.value = userResult.records || []; projects.value = projectResult.records || []; priorityOptions.value = (dicts.find(item => item.type === 'taskPriority')?.items || []).map(item => ({ label: item.label, value: item.value })); if (!priorityOptions.value.some(item => item.value === defaults.priority)) defaults.priority = priorityOptions.value[0]?.value; rows.value.forEach(row => { row.priority = defaults.priority }) } catch (error) { message.error(error.message || '页面初始化失败') } })
</script>

<style scoped>
.batch-task-page{min-height:100%;padding:20px 24px;background:#f6f8fc}.page-header,.toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px}.page-header{margin-bottom:16px}.page-header h2{margin:0 0 6px;font-size:20px}.page-header span,.toolbar{color:#8c8c8c;font-size:13px}.batch-card{margin-bottom:14px;border-radius:8px;box-shadow:0 2px 10px rgb(31 41 55 / 6%)}.defaults-card :deep(.ant-form){display:flex;flex-wrap:wrap;gap:8px 18px;align-items:center}.defaults-card :deep(.ant-form-item){margin:0}.defaults-card :deep(.ant-select),.defaults-card :deep(.ant-picker),.defaults-card :deep(.ant-input){width:180px}.toolbar{margin-bottom:14px}.table-wrap{overflow:auto}.task-table{width:100%;min-width:1340px;border-collapse:separate;border-spacing:0;table-layout:fixed}.task-table th,.task-table td{height:54px;padding:6px 8px;border-right:1px solid #edf0f3;border-bottom:1px solid #edf0f3;text-align:left;vertical-align:middle}.task-table th{height:42px;background:#fafbfc;color:#262626;white-space:nowrap}.task-table th:first-child,.task-table td:first-child{border-left:1px solid #edf0f3}.task-table th{border-top:1px solid #edf0f3}.task-table th:nth-child(1),.task-table td:nth-child(1){width:36px;text-align:center}.task-table th:nth-child(2),.task-table td:nth-child(2){width:56px;text-align:center}.task-table th:nth-child(3){width:190px}.task-table th:nth-child(4){width:120px}.task-table th:nth-child(5){width:110px}.task-table th:nth-child(6),.task-table th:nth-child(7){width:145px}.task-table th:nth-child(8){width:140px}.task-table th:nth-child(9){width:180px}.task-table th:nth-child(10){width:150px}.task-table th:nth-child(11),.task-table td:nth-child(11){position:sticky;right:0;z-index:2;width:170px;background:#fff;box-shadow:-2px 0 5px rgb(0 0 0 / 4%)}.task-table th:nth-child(11){z-index:3;background:#fafbfc}.task-table :deep(.ant-picker),.task-table :deep(.ant-select),.task-table :deep(.ant-input),.task-table :deep(.ant-input-textarea){width:100%}.name-cell{display:flex;align-items:center;gap:5px}.name-cell span{color:#bfbfbf}@media(max-width:900px){.defaults-card :deep(.ant-form-item){width:100%}.defaults-card :deep(.ant-select),.defaults-card :deep(.ant-picker),.defaults-card :deep(.ant-input){width:100%}.toolbar{align-items:flex-start;flex-direction:column}}
</style>
